### ISSUE TITLE
allocate gives the undivided penny to the first ratio

### ISSUE THREAD

**Issue by ahmedkandel** [dinerojs/dinero.js#144]
**Describe the bug**
When using allocate it gives the undivided penny to the first ratio, While I would expect it to be given to the highest fraction of penny like rounding up on high and down on all the other ratios.

I am using allocate to calculate a price discount as follows:
`Dinero({ amount: price }).allocate([discount, 100-discount])`
If the discount has a small fraction of a penny it moves the whole penny to the discount while I expect it to move it to discount only if the fraction of a half penny or more.

**To reproduce**
`Dinero({ amount: 1003 }).allocate([49, 51])[0].toUnit()` \\4.92 while expected 4.91
`Dinero({ amount: 1003 }).allocate([49, 51])[1].toUnit()` \\5.11 while expected 5.12

**Expected behavior**
When using allocate the undivided fraction goes to the ratio that gives the highest fraction of penny. Otherwise, if the fractions are equal goes to the first one.

**Comment by nickpalmer** [comment]
This is the documented behavior of allocate per the API. You can control which bucket gets the penny using the ordering of the buckets. If it picked the largest bucket always, users who want the extra penny to always end up on one side or the other would be unable to decide. This is decidedly not a bug to me, it is a feature, and a deliberate one.

While it might be convenient to have it allocate extra pennies to the highest amount, you can get the same results outside Dinero by ordering the percentage you want to get the extra penny to first in your own code.

Also, I am not sure why you are using allocate in this way. Why not just multiply by discount / 100 and specify a rounding mode to get the behavior you want for the discount. You could change the round up or down based on percentage if you really care about the bigger bucket getting the penny and then subtract from the price if you need the other bucket.

Arguing that percentage should include an optional rounding mode I could understand since it is doing a multiply by discount / 100 under the covers and just using the global rounding mode, but you can do the same with multiply yourself.

**Comment by sarahdayan** [comment]
Hey @ahmedkandel! ahmedkandelAs @nickpalmer said, this is intended behavior. You can control what bucket(s) get the remainder by sorting them first.
