### ISSUE TITLE
custom functions as convert endpoint

### ISSUE THREAD

**Issue by tomslutsky** [dinerojs/dinero.js#175]
In the existing api I can't find a way to implement caching for exchange api results.
As I see it the convert configurations require either string or promise.
I suggest providing an option to use an async function the will receive {from, to} as parameters and return a promise resolving to the rates result.
that way custom logic could be applied to the api calls

**Comment by sarahdayan** [comment]
Hey @tomslutsky! The way I designed [`convert`](https://dinerojs.com/module-dinero#~convert) in Dinero.js v1 was a gross mistake. I implemented a workaround so that you can fetch your rates yourself, cache them on your end, and pass them down to the function.

```js
// Fetched on your end
const rates = {
  rates: {
    EUR: 0.81162,
  },
};

Dinero({ amount: 500 }).convert('EUR', {
  endpoint: new Promise.resolve(rates),
});
```

If you're willing to use [v2](https://v2.dinerojs.com/docs), the API for [`convert`](https://v2.dinerojs.com/docs/api/conversions/convert) is even more straightforward, and the function is synchronous.
