### ISSUE TITLE
multiply not works as expected

### ISSUE THREAD

**Issue by approached** [dinerojs/dinero.js#177]
Multiply not works as expected. Result is wrong.

**To reproduce**
```js
    let test = Dinero({amount: 9999, currency: 'EUR'});
    test = test.divide(119);
    test = test.multiply(100);

    console.log(test.setLocale('de-DE').toFormat());  => 84,00 €
```

Expected result: 84,03 €

**Comment by maxyha** [comment]
@approached : Not sure if this is a problem of Dinero.multiply().

What you are looking for is a quotient, obviously for VAT calculations. Such a quotient can and should have a greater precision than 2 digits after decimal point. Dinero.divide() will always round to the amount of digits after decimal points specified by its currency. For EUR the result will be rounded to €0.84 instead of 0.8403361... by definition of monetary calculations. This is a proper result for money calculations but is obviously not sufficient as a quotient you are seeking for your calculations. 

Do the following for receiving proper results:
```
let test = Dinero({amount: 9999, currency: 'EUR'});
test = test.multiply(100 / 119); 
```
this will calculate 99.99 * 0.8403361...  = 84.02521008...  and return you a Dinero object containing properly rounded €84.03

**Comment by approached** [comment]
@maxyha thx
