### ISSUE TITLE
Allow specifying roundingMode for Dinero.percentage

### ISSUE THREAD

**Issue by seankwalker** [dinerojs/dinero.js#208]
**Is your feature request related to a problem? Please describe.**

I was recently using Dinero to calculate percentages while needing to use a specific rounding mode (the context was that I was redoing calculations that had been previously done with a set rounding mode, so needed to faithfully reproduce the original calculations to be able to evaluate). I noticed that even though `percentage` uses `multiply` under the hood, unlike `multiply`, it does not support specifying a rounding mode to be used.

**Describe the solution you'd like**

`percentage` should have an optional `roundingMode` parameter.

**Describe alternatives you've considered**

One can also just use `multiply`, of course, but then what's the point of having the `percentage` convenience method?

**Additional context**

I noticed this idea was also brought up in a [comment](https://github.com/dinerojs/dinero.js/issues/144#issuecomment-653136024) in #144 when looking for duplicate issues before making this one.

Also, more than happy to make a PR implementing this. Just wanted to throw a feature request out first to make sure it's something the maintainers would want before submitting a PR!

**Comment by sarahdayan** [comment]
Hi @seankwalker and thanks for this thorough writeup.

It makes a lot of sense indeed, given the API, to let users provide an optional rounding mode. Feel free to open a PR if you're still up to it!

I've also just release [Dinero.js v2 alpha](https://v2.dinerojs.com/docs), which I would recommend using instead of v1 now. Calculations no longer rely on rounding modes, you retain the whole precision of the split number. Here's [a guide](https://v2.dinerojs.com/docs/faq/how-do-i-calculate-a-percentage) on how to calculate a percentage.

**Comment by seankwalker** [comment]
Oh wow, that's awesome news!! I'll definitely check out v2 alpha. Dinero has been a lifesaver for my team, so also thanks so much for the great work on this library 🙏 

Will open a PR for this! Thanks for the response @sarahdayan :)

**Comment by sarahdayan** [comment]
Thank you! I hope you enjoy v2, please drop some feedback in [discussions](https://github.com/dinerojs/dinero.js/discussions) when you migrate 🙂
