### ISSUE TITLE
[Bug]: toUnit does not round values with custom scales, when using dinero.js rounding functions

### ISSUE THREAD

**Issue by jall** [dinerojs/dinero.js#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `digits` argument to `toUnit` appears to be ignored in v2.0.0-alpha6 when a dinero value with a custom scale is passed: no rounding takes place

However, if I import the rounding function `halfUp` from `@dinero.js/core` directly, it works

Puzzled as to why this is, as the `dinero.js` package exports the rounding functions directly from `@dinero.js/core` anyway! I've never installed any other version of this package, and both `package.lock` and `node_modules` show all versions as `2.0.0-alpha.6`

### Expected behavior

The value is rounded to the specified number of digits and scaled appropriately

## Failing

```ts
import { dinero, halfUp, toUnit } from "dinero.js"
import {GBP} from "@dinero.js/currencies"

const d1 = dinero({amount: 123456789, scale: 5, currency: GBP})

const rounded = toUnit(d1, {
  digits: 2,
  round: halfUp,
})

console.log(rounded)
// Expected: 1234.57
// Actual  : 1234.56789
```

## Working: "@dinero.js/core" rounding function import

```ts
import { dinero, toUnit } from "dinero.js"
import { halfUp } from "@dinero.js/core"
import {GBP} from "@dinero.js/currencies"

const d1 = dinero({amount: 123456789, scale: 5, currency: GBP})

const rounded = toUnit(d1, {
  digits: 2,
  round: halfUp,
})

console.log(rounded)
// Expected: 1234.57
// Actual  : 1234.57
```

## Working: no custom scale

```ts
import { dinero, toUnit, halfUp } from "dinero.js"
import {GBP} from "@dinero.js/currencies"

const d1 = dinero({amount: 123456789, currency: GBP})

const rounded = toUnit(d1, {
  digits: 1,
  round: halfUp,
})

console.log(rounded)
// Expected: 12345678.9
// Actual  : 12345678.9
```

### Version

2.0.0-alpha.6

### Environment

macOS 11.5, Node 14.16.1, Typescript 4.3.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sarahdayan** [comment]
Hey @jall, that's a known bug that was fixed in https://github.com/dinerojs/dinero.js/pull/293. The rounding functions weren't properly re-exported from `dinero.js`, which is why it's failing. Right now, you're passing `undefined`.

This will go out in the `2.0.0-alpha.7` release which I'll do later today (see https://github.com/dinerojs/dinero.js/pull/295).

Note that the `toUnit` function currently has problems that I'm discussing in https://github.com/dinerojs/dinero.js/issues/294. Potential solutions might change its return type, or replace it with a different function. I'd love for you to participate the conversation!

Closing this once I release `2.0.0-alpha.7`.
