### ISSUE TITLE
v2 - Dynamically importing currencies

### ISSUE THREAD

**Issue by gregholland** [dinerojs/dinero.js#326]
Hello. I'm playing around with the v2 Alpha and something I can't work out is how to dynamically use currencies. In your stripe example, you've got it hardcoded to USD - what if the value coming from Stripe is CAD and you don't know that until the request is made?

**Comment by sarahdayan** [comment]
Hi @gregholland!

I don't know exactly what your use case is, so I'll make assumptions to cover the problem. Don't hesitate to reply with more details if this needs further discussion.

When you're accepting payments, you usually know in advance what currencies you're able to process. This depends on where your business is established and the service you're using (e.g., see what [Stripe supports](https://stripe.com/docs/currencies)).

So, assuming you're accepting 135 different currencies, you could either load them all at once, or lazy-load them using dynamic imports (`import()`).

If you have no idea what currency you might receive, then you can dynamically construct a currency object once you do know. But again, this sounds like an unusual use case and I'd need to know more about your specific situation to guide you here.

**Comment by gregholland** [comment]
Hey, thanks for the speedy reply! So we support 5 currencies right now. For now i'm just importing them all. 
```js
import * as currencies from '@dinero.js/currencies'
``` 
Then I can do this which is essentially the same as v1.
```js
const currency = 'CAD' // this would be coming from an API/DB, but you get the idea.
const total = dinero({
  amount,
  currency: currencies[currency]
})
```
I guess there isn't anything wrong with this approach, it just adds a bit more code each time compared to v1. Anyhow, thanks for all the hard work on this!

**Comment by sarahdayan** [comment]
I would recommend importing only the five you need, instead of the full package. There are 165 currency objects in the ISO 4217 directory right now, and the package also exports amended versions so you'll end up with a larger bundle than necessary. I don't know if the code you're showing is front end or back end, but if this front end, you definitely want to reduce this overhead.

And yes, if your back end receives the customer's chosen currency as a string, creating a currency map can be a good solution. An alternative could be to receive the currency as a stringified Dinero object. The additional code should be trivial, and not matter much since the charge happens on the server anyway.
