### ISSUE TITLE
Custom currencies 

### ISSUE THREAD

**Issue by osdiab** [dinerojs/dinero.js#36]
This is not super important given that you can just output to a currency and then find/replace the currency symbol, but digital/crypto currencies with their own names are becoming more and more commonplace, so it would be cool if you could, instead of using an ISO world currency, optionally throw in your own currency symbol or text.

**Comment by sarahdayan** [comment]
Hi @osdiab. For now Dinero only supports ISO 4217 currency code, mostly because it uses the ECMAScript Internationalization API for formatting.

Relying on this API has limits, which is why I'm considering either extending its behavior, or moving away from it in v2. For that reason, I'm not closing the door but if it happens, this won't be in v1.

Thanks for the suggestion. You're not the only one who asked for it and I'm hearing you.

**Comment by osdiab** [comment]
what options do you have in mind as an alternative to those internationalization APIs? @sarahdayan

**Comment by sarahdayan** [comment]
Hey! I just published a RFC for Dinero.js v2 🚀 It tackles this specific problem.

I would love to have your feedback on it: https://github.com/dinerojs/rfcs/pull/1

cc @osdiab

**Comment by xenoterracide** [comment]
this is what I came looking for, our problem is a sort of "rewards currency" you can spend "points" to buy things.

**Comment by frolovdev** [comment]
@xenoterracide @osdiab You can use https://github.com/frolovdev/easymoney

Maybe it solves your problems

**Comment by sarahdayan** [comment]
Hey @xenoterracide @osdiab! I just released [Dinero.js v2 in alpha](https://v2.dinerojs.com/docs), and custom currencies are supported out of the box ✨

Check out the guide on [currency](https://v2.dinerojs.com/docs/core-concepts/currency) to learn how to do it. You also have an advanced guide on how to handle [non-decimal currencies](https://v2.dinerojs.com/docs/advanced/formatting-non-decimal-currencies).

**Comment by osdiab** [comment]
Sweet, thanks!

Omar

**Comment by alexdunae** [comment]
Awesome @sarahdayan - thank you!!
