### ISSUE TITLE
Specifying Currency With Three-Digit ISO 4217 Code

### ISSUE THREAD

**Issue by gphendry** [dinerojs/dinero.js#67]
In addition to being able to specify currency codes by the ISO-standard three-letter short code, it would also be helpful to be able to pass in the three-digit ISO 4217 code as a way to specify the currency. 

In addition to being able to define currency like this with the standard three-letter string:
`Dinero({ currency: 'USD' }).getCurrency();`
The user should also be able to pass in the three-digit ISO currency code:
`Dinero({ currency: 840 }).getCurrency();`
which in this case would set the currency to USD the same as passing in the string.

I've tried using another library to get the three-letter short code from the number but it would be very helpful if Dinero supported this natively given that it is part of the ISO currency standards and using the numerical ISO code is often preferred in many use cases.

**Comment by sarahdayan** [comment]
Hey @gphendry and thanks for the proposal!

Dinero v2 will have a [currency service](https://github.com/dinerojs/rfcs/blob/feat/v2/0001-dinerojs-v2.md#currency-service) that makes it easier to pass a currency.

Can you tell me what passing the numeric code instead of the alpha one would solve?

**Comment by gphendry** [comment]
A lot of payments systems use the three-digit ISO currency code instead of the string representation. 

Having the ability to specify currency with the ISO code would make using Dinero in conjunction with these systems much easier and removes the need for doing intermediate conversions from the ISO code to its string representation.

**Comment by sarahdayan** [comment]
Hey there! [Dinero.js v2 alpha](https://v2.dinerojs.com/docs) is out and expects currency as `Currency` objects.

Natively passing currency by code isn't in the design because it would require you to load all available currencies, which you probably don't want to keep your front-end bundle as light as possible.

However, you can build your own helper function for the currencies you do support in your app if you want to do that.

For example, if you support USD and EUR:

```js
import { dinero } from 'dinero.js';
import { USD, EUR } from '@dinero.js/currencies';

function dineroFromCurrencyCode({ amount, currency: currencyCode, scale }) {
  const codes = {
    840: USD,
    978: EUR,
  };

  const currency = codes[currencyCode];

  return dinero({ amount, scale, currency });
}

const d = dineroFromCurrencyCode({ amount: 100, currency: 840 });
```

You can see it in action in this [sandbox](https://codesandbox.io/s/gifted-germain-4jzom?file=/main.js).
