### ISSUE TITLE
[Bug]: build steps are run twice during CI

### ISSUE THREAD

**Issue by johnhooks** [dinerojs/dinero.js#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

During local development I've notice when running `yarn install` it will call the `prepare` scripts of all the workspace packages. Is this intended behavior? 

This also happens in the CI build pipeline. So `babel`, `tsc` and `api-extractor` are all run twice. Because they are run after `yarn install` and also during `yarn build`. What is the right way to remove this duplication?

>Certain script names are special. If defined, the preinstall script is called by yarn before your package is installed. For compatibility reasons, scripts called install, postinstall, prepublish, and prepare will all be called after your package has finished installing.

[^^ reference](https://classic.yarnpkg.com/en/docs/package-json#toc-scripts)

### Expected behavior

Build steps should not be duplicated in CI or local development.

### Steps to reproduce

`yarn install`
`yarn build`

### Version

2.0.0-alpha.9

### Environment

Node.js 16.13.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by johnhooks** [comment]
I've also noticed in CI all the examples are built along with the packages. Is this intended behavior?

**Comment by johnhooks** [comment]
The `prepare` script is bring rerun in every CircleCI job. So to complete the whole workflow it is run 6 times unnecessary.

**Comment by sarahdayan** [comment]
This was initially necessary to check the types and run tests.

It's no longer necessary during tests since https://github.com/dinerojs/dinero.js/commit/2d408ca74b19d00900f67126059e271e3a3fffc4, and no longer necessary during type checks since https://github.com/dinerojs/dinero.js/commit/676b1b658d1137be8ffbf120d6b5ac9b4a2e857c.

It's still necessary to have access to the built artifacts, though, when checking the build size and when building the documentation site (for [this page](https://v2.dinerojs.com/docs/getting-started/optimizing-for-production) to exist).

The CircleCI job that tests the build size seems to be the only one that requires a build now. In this case, we might do it directly in `config.yml` (and just the UMD builds) instead.

Regarding the release, Ship.js takes care of building anyway, so building on prepare isn't useful.

Finally, regarding the documentation, this is taken care of not in the CI but directly on Vercel, using their GitHub integration. We could handle this by building as the first step in all `website:` scripts. Bonus if we can build only if necessary so we don't re-build whenever we stop and start the server locally.

What do you think?

**Comment by johnhooks** [comment]
This will need to be reconsidered if 

**`.codesandbox/ci.json`**
```json
{
  "buildCommand": false,
  "^": "buildCommand is false because `yarn prepare` is going to build packages anyway.",
}
```

**Comment by johnhooks** [comment]
**Take aways**

- Removing `prepare` from all the package scripts would be okay.
   *NOTE:* I am going to add a `prepare` script to the currencies package to generate the currency files in PR https://github.com/dinerojs/dinero.js/pull/670. That would be necessary many other steps of the workflow. (Though its a pretty quick step)

- Having a `build` job in the workflow is still necessary, but none of the jobs other than `test_size` require it.
- Most jobs don't need to attach the workspace, unless they need the build artifacts, like `test_size`
- Building the website and examples in CircleCI isn't necessary because they are part of the `ci/codesandbox` and integrations with Vercel.

**Comment by johnhooks** [comment]
Should the example projects have `"private": true` in their `package.json`?

They aren't published to `npm` and add it would disable building them in CircleCI because all the `lerna` commands have the `--no-private` flag applied.

**Comment by johnhooks** [comment]
@sarahdayan is the `test_types` job necessary? The `build` job runs `tsc` and `api-extractor` to generate the declaration files. If there is a type error the `build` job will fail.

**Comment by sarahdayan** [comment]
@johnhooks Hmm I guess it's useful to see at a glance, in the CI, what has failed. If the `test_types` job is red I know immediately what the issue is, so does the person who opened a PR but doesn't have access to CircleCI.

If this happens in the `build` job you don't immediately know what the problem is.

Is `test_types` a bottleneck right now?

**Comment by johnhooks** [comment]
It's just a duplication. If its helpful to you, then I'll shelve the idea. If I can figure out how to use Turbo effectively in CI, it will be a none issue because the build steps could be structured in a way to prevent a second call to `tsc` but still show you the error is a type issue.
