### ISSUE TITLE
convertPrecision problem

### ISSUE THREAD

**Issue by ftaiolivista** [dinerojs/dinero.js#72]
From precision 8 got 3.33 as expected
```
    Dinero({ amount: 333333336, precision: 8 })
        .convertPrecision(2)
        .toUnit()

// 3.33
```
From precision 9 got 0!?? what's wrong?
```
    Dinero({ amount: 3333333336, precision: 9 })
        .convertPrecision(2)
        .toUnit()

// 0
```

**Comment by thekevinbrown** [comment]
The issue was that we weren't handling very small numbers correctly within the library. As soon as they represented in scientific notation, we stopped being able to determine their fractional digits because we were inspecting the string and not handling this case.

I've opened #77 which fixes this issue and adds tests to ensure the behaviour doesn't reappear.
