### ISSUE TITLE
Support ISO 4217 minor currency units (cents vs fils)

### ISSUE THREAD

**Issue by montanaflynn** [dinerojs/dinero.js#9]
If you want the library to support all ISO 4217 currencies as suggested in the documentation you may want to rethink using "cents" as the amount value. For instance some currencies do not have a [minor currency equivalent](https://en.wikipedia.org/wiki/ISO_4217#Treatment_of_minor_currency_units_(the_%22exponent%22))  (e.g. Japanese Yen) and others have different exponents (e.g. The Iraqi Dinar is divided into 1000 fils. The United States Dollar is divided into 100 cents.) so maybe that should be handled by the library. You can find all the [currencies and their minor currency exponent here](https://en.wikipedia.org/wiki/ISO_4217#Active_codes).

```js
// this should be 1 Iraqi Dinar not 10
Dinero({ amount: 1000, currency: 'IQD' })
```

**Comment by sarahdayan** [comment]
Thank you @montanaflynn for raising this issue.

I'm definitely considering offering better support for all ISO 4217 currencies. Instead of revising the usage of sub-units as the amount (which covers many cases) there could be something to do with the exponent. For example, you could indicate it as you create a Dinero object and it would become the divisor for every manipulation.

```
Dinero({ amount: 1000, currency: 'IQD', exponent: 3 })
```

One step further would be creating a Currency service, which would allow currency assertions and automatic exponent inclusion. This would need to be maintained though.

**Comment by pawel-buczkowski-payu** [comment]
Your library is really cool!

But I really need this feature described in this issue. When do you plan to release v2?

BTW. It would be also nice to add a similar feature in toFormat function: when I use this function ex. toFormat('$0,0.00') I have to type so many zeros (at the end, after dot) as the currency precision is. It would be nice to have a way to define format like: toFormat('$0,0.#'), so the script will convert it to appropriate number of digits depending on currency precision. So for number 1234 it would give results: 12.34 for EUR, 1,234 for JPY and 1.234 for IQD :)

**Comment by andyburke** [comment]
Although it is uncommon (I only see few in Wikipedia's list of circulating currencies: https://en.wikipedia.org/wiki/List_of_circulating_currencies ), some currencies are not base-10:

```
  |--------------------|----------|---------|----------|----------------|-----------------|
  | State or territory | Currency | Symbol  | ISO code | Fractionalunit | Number to basic |
...
  | Madagascar         | ...      | Ar      | MGA      | Iraimbilanja   | 5               |
```

Instead of an 'exponent' setting, should there just be a 'base' setting? In the case above, it would be 5.

Perhaps it's uncommon enough so as not to matter? I count only 3 currencies in the list I linked that are not base-10 (all of those are base-5).

**Comment by gvx** [comment]
@andyburke In those cases, would it not make sense to simply use an exponent of 1, and count in theoretical halves of those fractional units? I guess that depends on if the users of those currencies would find it intuitive that some website displays 0.2 of the main unit instead of 1 fractional unit.

**Comment by sarahdayan** [comment]
Hey! I just published a RFC for Dinero.js v2 🚀 It tackles this specific problem.

I would love to have your feedback on it: https://github.com/dinerojs/rfcs/pull/1

cc @montanaflynn @pawel-buczkowski-payu @andyburke @gvx

**Comment by sarahdayan** [comment]
Hey again! I just released [Dinero v2 in alpha](https://v2.dinerojs.com/docs) 🙂 It provides core support for various exponents at the currency level, and exposes ISO 4217 currency objects for convenience.

```js
import { dinero, toFormat } from 'dinero.js';
import { IQD } from '@dinero.js/currencies';

const d1 = dinero({ amount: 1000, currency: IQD });

toFormat(d1, ({ amount, currency }) => `${currency.code} ${amount}`); // "IQD 1"
```

Here's a [sandbox](https://codesandbox.io/s/inspiring-architecture-362xd?file=/main.js) if you want to see it in action.

I'll close this issue since v1 has a workaround and v2 fixes it.
